generate_visualizations <- function(data) {
 dir.create("output/charts",recursive=TRUE,showWarnings=FALSE);save<-function(p,n,w=10,h=6)ggplot2::ggsave(file.path("output/charts",n),p,width=w,height=h,dpi=300,bg="white");th<-ggplot2::theme_minimal()
 top<-data|>dplyr::filter(!is.na(Global_Sales))|>dplyr::arrange(dplyr::desc(Global_Sales))|>dplyr::slice_head(n=10);top$Name<-make.unique(as.character(top$Name))
 save(ggplot2::ggplot(top,ggplot2::aes(reorder(Name,Global_Sales),Global_Sales))+ggplot2::geom_col()+ggplot2::coord_flip()+ggplot2::labs(title="Top 10 Best-Selling Games",x="Game",y="Global sales (millions)")+th,"top_games.png")
 p<-data|>dplyr::filter(!is.na(Platform),!is.na(Global_Sales))|>dplyr::group_by(Platform)|>dplyr::summarise(sales=sum(Global_Sales),games=dplyr::n(),.groups="drop")
 save(ggplot2::ggplot(dplyr::slice_max(p,sales,n=10,with_ties=FALSE),ggplot2::aes(reorder(Platform,sales),sales))+ggplot2::geom_col()+ggplot2::coord_flip()+ggplot2::labs(title="Top Platforms by Sales",x="Platform",y="Global sales (millions)")+th,"platform_sales.png")
 g<-data|>dplyr::filter(!is.na(Genre),Genre!="Unknown",!is.na(Global_Sales))|>dplyr::group_by(Genre)|>dplyr::summarise(sales=sum(Global_Sales),.groups="drop")
 save(ggplot2::ggplot(g,ggplot2::aes(reorder(Genre,sales),sales))+ggplot2::geom_col()+ggplot2::coord_flip()+ggplot2::labs(title="Sales by Genre",x="Genre",y="Global sales (millions)")+th,"genre_sales.png")
 b<-data|>dplyr::filter(!is.na(Publisher),Publisher!="Unknown",!is.na(Global_Sales))|>dplyr::group_by(Publisher)|>dplyr::summarise(sales=sum(Global_Sales),.groups="drop")|>dplyr::slice_max(sales,n=10,with_ties=FALSE)
 save(ggplot2::ggplot(b,ggplot2::aes(reorder(Publisher,sales),sales))+ggplot2::geom_col()+ggplot2::coord_flip()+ggplot2::labs(title="Top Publishers",x="Publisher",y="Global sales (millions)")+th,"publisher_sales.png")
 y<-data|>dplyr::filter(!is.na(Year),Year>=1950,Year<=as.numeric(format(Sys.Date(),"%Y"))+2)|>dplyr::group_by(Year)|>dplyr::summarise(sales=sum(Global_Sales,na.rm=TRUE),games=dplyr::n(),.groups="drop")
 save(ggplot2::ggplot(y,ggplot2::aes(Year,sales))+ggplot2::geom_line()+ggplot2::geom_point()+ggplot2::labs(title="Global Sales by Year",x="Year",y="Sales (millions)")+th,"yearly_sales.png")
 save(ggplot2::ggplot(y,ggplot2::aes(Year,games))+ggplot2::geom_line()+ggplot2::geom_point()+ggplot2::labs(title="Game Releases by Year",x="Year",y="Game count")+th,"yearly_releases.png")
 l<-c(NA_Sales="North America",EU_Sales="Europe",JP_Sales="Japan",Other_Sales="Other");cs<-intersect(names(l),names(data));r<-data.frame(region=unname(l[cs]),sales=vapply(cs,function(n)sum(data[[n]],na.rm=TRUE),numeric(1)))
 save(ggplot2::ggplot(r,ggplot2::aes(region,sales,fill=region))+ggplot2::geom_col(show.legend=FALSE)+ggplot2::labs(title="Regional Sales",x="Region",y="Sales (millions)")+th,"regional_sales.png")
 q<-data|>dplyr::filter(!is.na(Genre),Genre!="Unknown")|>dplyr::group_by(Genre)|>dplyr::summarise(dplyr::across(dplyr::all_of(cs),~sum(.x,na.rm=TRUE)),.groups="drop")|>tidyr::pivot_longer(dplyr::all_of(cs),names_to="region_code",values_to="sales");q$region<-unname(l[q$region_code])
 save(ggplot2::ggplot(q,ggplot2::aes(Genre,sales,fill=region))+ggplot2::geom_col(position="dodge")+ggplot2::labs(title="Genre Sales by Region",x="Genre",y="Sales (millions)")+th+ggplot2::theme(axis.text.x=ggplot2::element_text(angle=35,hjust=1)),"genre_regional_sales.png",11,7)
 save(ggplot2::ggplot(dplyr::slice_max(p,games,n=15,with_ties=FALSE),ggplot2::aes(reorder(Platform,games),games))+ggplot2::geom_col()+ggplot2::coord_flip()+ggplot2::labs(title="Games per Platform (Top 15)",x="Platform",y="Game count")+th,"games_per_platform.png")
 save(ggplot2::ggplot(dplyr::filter(data,!is.na(NA_Sales),!is.na(Global_Sales)),ggplot2::aes(NA_Sales,Global_Sales))+ggplot2::geom_point(alpha=.35)+ggplot2::labs(title="North America vs Global Sales",x="NA sales (millions)",y="Global sales (millions)")+th,"regional_vs_global_sales.png")
 cat("Generated 10 PNG charts.\n");invisible(TRUE)
}
